# Generated by Django 5.0.2 on 2024-05-05 08:46

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarModel",
            fields=[
                ("calendar_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("note", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventModel",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "organised_by",
                    models.CharField(
                        choices=[("college", "college"), ("commitee", "commitee")],
                        max_length=50,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("hackathon", "hackathon"),
                            ("cultural", "cultural"),
                            ("datathon", "datathon"),
                            ("startup", "startup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobBoardModel",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=50)),
                (
                    "subtype",
                    models.CharField(
                        choices=[("internship", "internship"), ("Job", "job")],
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("Offline", "offline"), ("Online", "online")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorshipModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorships_mentee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorships_mentor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotesModel",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("note_title", models.TextField()),
                ("note_description", models.TextField()),
                ("subject", models.TextField()),
                ("department", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "One Star"),
                            (2, "Two Stars"),
                            (3, "Three Stars"),
                            (4, "Four Stars"),
                            (5, "Five Stars"),
                        ]
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="raw/",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostModel",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("deadline", models.DateTimeField()),
                ("post_url", models.URLField()),
                ("description", models.TextField()),
                ("likes", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("Job", "job_board"), ("Event", "event")],
                        max_length=10,
                    ),
                ),
                ("is_interested", models.BooleanField(default=False)),
                ("date_updated", models.DateField(auto_now=True)),
                ("date_uploaded", models.DateField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="images/",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideolinksModel",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=100)),
                ("sem", models.IntegerField()),
                ("topics", models.CharField(max_length=100)),
                ("links", models.URLField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
