# Generated by Django 5.0.3 on 2024-04-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sapid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('expertise', models.CharField(blank=True, max_length=100)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
