# Generated by Django 5.0.3 on 2024-04-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
