# Generated by Django 5.0.2 on 2024-05-03 16:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notesmodel",
            name="document",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
