# Generated by Django 5.0.2 on 2024-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_mentorshipmodel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobboardmodel",
            name="location",
            field=models.CharField(default="Remote", max_length=50),
        ),
    ]
