# Generated by Django 5.0.2 on 2024-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_jobboardmodel_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobboardmodel",
            name="job_title",
            field=models.CharField(
                choices=[
                    ("Software Engineer", "Software Engineer"),
                    ("Data Analyst", "Data Analyst"),
                    ("Web Developer", "Web Developer"),
                    ("UI/UX Designer", "UI/UX Designer"),
                    ("Project Manager", "Project Manager"),
                    ("Business Analyst", "Business Analyst"),
                    ("Backend Developer", "Backend Developer"),
                    ("Machine Learning Engineer", "Machine Learning Engineer"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
