# Generated by Django 5.0.3 on 2024-04-02 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='videolinksModel',
            fields=[
                ('subject', models.CharField(max_length=100)),
                ('sem', models.IntegerField(max_length=8)),
                ('topics', models.CharField(max_length=100)),
                ('links', models.URLField()),
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('sapid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
