# Generated by Django 5.0.3 on 2024-04-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_videolinksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='postModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('post_url', models.URLField()),
                ('description', models.TextField()),
                ('likes', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Job', 'job_board'), ('Event', 'event')], max_length=10)),
                ('is_interested', models.BooleanField(default=False)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_uploaded', models.DateField(auto_now=True)),
                ('sapid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
