# Generated by Django 5.0.2 on 2024-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_jobboardmodel_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobboardmodel",
            name="contact_no",
            field=models.CharField(default=9999999999, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobboardmodel",
            name="requirements",
            field=models.TextField(default="No backlogs"),
            preserve_default=False,
        ),
    ]
