# Generated by Django 5.0.2 on 2024-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_notesmodel_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notesmodel",
            name="document",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
