# Generated by Django 5.0.2 on 2024-05-03 17:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_notesmodel_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notesmodel",
            name="document",
            field=models.ImageField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="raw/",
            ),
        ),
    ]
