# Generated by Django 4.2.7 on 2024-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobboardmodel_contact_no_jobboardmodel_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboardmodel',
            name='job_title',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Data Analyst', 'Data Analyst'), ('Web Developer', 'Web Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Project Manager', 'Project Manager'), ('Business Analyst', 'Business Analyst'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Machine Learning Engineer', 'Machine Learning Engineer')], max_length=50),
        ),
    ]
