# Generated by Django 5.0.3 on 2024-04-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolinksmodel',
            name='sem',
            field=models.IntegerField(),
        ),
    ]
