# Generated by Django 4.2.7 on 2024-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_jobboardmodel_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='organised_by',
            field=models.CharField(choices=[('college', 'college'), ('commitee', 'commitee')], default=('college', 'college'), max_length=50),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='subtype',
            field=models.CharField(choices=[('hackathon', 'hackathon'), ('cultural', 'cultural'), ('datathon', 'datathon'), ('startup', 'startup')], default=('hackathon', 'hackathon'), max_length=20),
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
    ]
