# Generated by Django 5.0.3 on 2024-04-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_videolinksmodel_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventModel',
            fields=[
                ('postmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.postmodel')),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('organised_by', models.CharField(choices=[('college', 'college'), ('commitee', 'commitee')], max_length=50)),
                ('subtype', models.CharField(choices=[('hackathon', 'hackathon'), ('cultural', 'cultural'), ('datathon', 'datathon'), ('startup', 'startup')], max_length=20)),
            ],
            bases=('accounts.postmodel',),
        ),
        migrations.CreateModel(
            name='jobBoardModel',
            fields=[
                ('postmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.postmodel')),
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('subtype', models.CharField(choices=[('internship', 'internship'), ('Job', 'job')], max_length=10)),
                ('mode', models.CharField(choices=[('Offline', 'offline'), ('Online', 'on;ine')], max_length=10)),
            ],
            bases=('accounts.postmodel',),
        ),
    ]
