# Generated by Django 4.2 on 2024-04-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_eventmodel_jobboardmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobboardmodel",
            name="mode",
            field=models.CharField(
                choices=[("Offline", "offline"), ("Online", "online")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="notesModel",
            fields=[
                ("note_id", models.IntegerField(primary_key=True, serialize=False)),
                ("note_title", models.TextField()),
                ("note_description", models.TextField()),
                ("subject", models.TextField()),
                ("department", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "One Star"),
                            (2, "Two Stars"),
                            (3, "Three Stars"),
                            (4, "Four Stars"),
                            (5, "Five Stars"),
                        ]
                    ),
                ),
                ("document", models.FileField(upload_to="documents/")),
                (
                    "sapid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("calendar_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("note", models.TextField()),
                (
                    "sapid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
    ]
