# Generated by Django 5.0.2 on 2024-05-04 14:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_notesmodel_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(
                default="",
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="images/",
            ),
            preserve_default=False,
        ),
    ]
