# Generated by Django 4.2.7 on 2024-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_postmodel_type_postmodel_organised_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipmodel',
            name='expertise',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
