# Generated by Django 4.2 on 2024-04-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("accounts", "0008_alter_jobboardmodel_mode_notesmodel_calendarevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user_ptr",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mentor",
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="sapid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.user"
            ),
        ),
        migrations.AlterField(
            model_name="notesmodel",
            name="sapid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.user"
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="sapid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.user"
            ),
        ),
        migrations.AlterField(
            model_name="videolinksmodel",
            name="sapid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.user"
            ),
        ),
        migrations.DeleteModel(
            name="Professor",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
