# Generated by Django 4.2 on 2024-04-03 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("accounts", "0009_remove_student_user_ptr_remove_user_mentor_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CalendarEvent",
            new_name="calendarModel",
        ),
    ]
