# Generated by Django 5.0.2 on 2024-06-06 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_notesmodel_rating_noterating"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobboardmodel",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobboardmodel",
            name="duration_in_months",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobboardmodel",
            name="upload_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
