# Generated by Django 5.0.2 on 2024-06-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_jobboardmodel_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobboardmodel",
            name="mode",
            field=models.CharField(
                choices=[
                    ("Offline", "offline"),
                    ("Online", "online"),
                    ("Hybrid", "hybrid"),
                    ("Remote", "remote"),
                ],
                max_length=10,
            ),
        ),
    ]
