# Generated by Django 5.0.2 on 2024-06-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_jobboardmodel_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobboardmodel",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
