# Generated by Django 5.0.2 on 2024-06-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_jobboardmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='subject',
            field=models.CharField(choices=[('ALL', 'ALL'), ('CS', 'CS'), ('IT', 'IT'), ('AIML', 'AIML'), ('AIDS', 'AIDS'), ('DS', 'DS'), ('IOT', 'IOT'), ('EXTC', 'EXTC'), ('ME', 'ME')], max_length=50),
        ),
        migrations.AlterField(
            model_name='videolinksmodel',
            name='subject',
            field=models.CharField(choices=[('ALL', 'ALL'), ('CS', 'CS'), ('IT', 'IT'), ('AIML', 'AIML'), ('AIDS', 'AIDS'), ('DS', 'DS'), ('IOT', 'IOT'), ('EXTC', 'EXTC'), ('ME', 'ME')], max_length=50),
        ),
    ]
