# Generated by Django 4.2 on 2024-04-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "sapid",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_number", models.CharField(max_length=10, unique=True)),
                ("expertise", models.CharField(blank=True, max_length=100)),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentees",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentication.user",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("authentication.user",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentication.user",
                    ),
                ),
                (
                    "current_year",
                    models.CharField(
                        choices=[
                            ("First Year", "First Year"),
                            ("Second Year", "Second Year"),
                            ("Third Year", "Third Year"),
                            ("Fourth Year", "Fourth Year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("branch", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("authentication.user",),
        ),
    ]
