# Generated by Django 5.0.2 on 2024-05-05 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("authentication.user",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_year",
                    models.CharField(
                        choices=[
                            ("First Year", "First Year"),
                            ("Second Year", "Second Year"),
                            ("Third Year", "Third Year"),
                            ("Fourth Year", "Fourth Year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("branch", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("authentication.user",),
        ),
    ]
