# Generated by Django 5.0.2 on 2024-04-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mentors",
            field=models.ManyToManyField(blank=True, to="authentication.user"),
        ),
    ]
